// Exhaustive coverage for scoring v2: every one of the 4^9 = 262,144 answer combinations is run
// through the recommender on the REAL database with a seeded roll, plus many rolls on a sample of
// profiles. Writes test-results/coverage.md. Hard assertions are the invariants and the agreed
// coverage targets (REQUIREMENTS section 10). Unreachable data is reported, never edited.
import { describe, expect, it } from "vitest";
import { mkdirSync, writeFileSync } from "node:fs";
import { QUESTIONS } from "@/lib/questions";
import { WORD_DIM, buildProfile, cafeTags, coffeeTags, prepare, recommendFromProfile, type Profile } from "@/lib/scoring";
import { mulberry32 } from "@/lib/rng";
import { loadData } from "./helpers";

const data = loadData();
const MULTI_PROFILES = 1000;
const MULTI_ROLLS = 25;

const BINS = 1000;
const hist = () => new Float64Array(BINS + 1);
const pct = (h: Float64Array, p: number) => {
  const total = h.reduce((a, b) => a + b, 0);
  let acc = 0;
  for (let i = 0; i <= BINS; i++) { acc += h[i]; if (acc >= p * total) return i / BINS; }
  return 1;
};

describe("exhaustive coverage over all answer combinations (scoring v2)", () => {
  it("meets the invariants and the coverage targets, and writes the report", () => {
    const prep = prepare(data);
    const eligibleRows = prep.rows.filter((r) => r.dims >= 3);
    const eligibleCafes = new Set(eligibleRows.map((r) => r.coffee.cafe));
    const eligibleCoffees = eligibleRows.length;

    const coffees = new Set<number>(), cafesSeen = new Set<string>();
    const cafeQuizzes = new Map<string, number>(), cafePicks = new Map<string, number>();
    const slotHist = [hist(), hist(), hist()], slotSum = [0, 0, 0], slotMin = [1, 1, 1];
    const violations: string[] = [];
    let quizzes = 0, picksTotal = 0, zeroScore = 0;
    const t0 = performance.now();

    const idx = new Array(9).fill(0);
    for (let n = 0; ; n++) {
      const profile: Profile = buildProfile(idx.map((a, qi) => QUESTIONS[qi].answers[a].tags));
      const picks = recommendFromProfile(profile, data, { rng: mulberry32(n * 2654435761), seed: n });
      quizzes++;
      if (picks.length !== 3) violations.push(`${picks.length} results`);
      if (new Set(picks.map((p) => p.cafeName)).size !== picks.length) violations.push("repeated cafe");
      picks.forEach((p, i) => {
        if (p.reason.length <= 10 || /undefined|null|\s{2,}/.test(p.reason)) violations.push(`bad reason: ${p.reason}`);
        if (p.coffee.cafe !== p.cafeName) violations.push("cafe mismatch");
        if (p.slot !== i + 1) violations.push("slot order");
        coffees.add(p.coffee.id); cafesSeen.add(p.cafeName);
        cafeQuizzes.set(p.cafeName, (cafeQuizzes.get(p.cafeName) ?? 0) + 1);
        cafePicks.set(p.cafeName, (cafePicks.get(p.cafeName) ?? 0) + 1);
        slotHist[i][Math.round(Math.min(1, p.quality) * BINS)]++;
        slotSum[i] += p.quality; slotMin[i] = Math.min(slotMin[i], p.quality);
        if (p.score === 0) zeroScore++;
        picksTotal++;
      });
      let i = 8;
      while (i >= 0 && ++idx[i] === 4) idx[i--] = 0;
      if (i < 0) break;
    }
    const msPer = (performance.now() - t0) / quizzes;
    expect(quizzes).toBe(4 ** 9);
    expect(violations.slice(0, 5)).toEqual([]);

    // many rolls on a sample of profiles: union reachability
    const rnd = mulberry32(2026);
    for (let k = 0; k < MULTI_PROFILES; k++) {
      const profile = buildProfile(QUESTIONS.map((q) => q.answers[Math.floor(rnd() * 4)].tags));
      for (let r = 0; r < MULTI_ROLLS; r++)
        for (const p of recommendFromProfile(profile, data, { rng: mulberry32(1_000_003 * (r + 1) + k), seed: r })) { coffees.add(p.coffee.id); cafesSeen.add(p.cafeName); }
    }

    const counts = [...cafePicks.values()].sort((a, b) => b - a);
    const top10 = counts.slice(0, 10).reduce((a, b) => a + b, 0) / picksTotal;
    const [topName, topN] = [...cafeQuizzes.entries()].sort((a, b) => b[1] - a[1])[0];
    const topShare = topN / quizzes;
    const mean = slotSum.map((s) => s / quizzes);

    // tag values no answer asks for
    const vocab = new Map<string, number>();
    for (const c of data.coffees) for (const [d, v] of coffeeTags(c)) vocab.set(`${d}:${v}`, (vocab.get(`${d}:${v}`) ?? 0) + 1);
    for (const cf of Object.values(data.cafes)) for (const [d, v] of cafeTags(cf)) vocab.set(`${d}:${v}`, (vocab.get(`${d}:${v}`) ?? 0) + 1);
    const asked = new Set(Object.entries(WORD_DIM).map(([w, d]) => `${d}:${w}`));
    const notAsked = [...vocab.keys()].filter((k) => !asked.has(k));
    const neverCafes = [...eligibleCafes].filter((c) => !cafesSeen.has(c));
    const f = (x: number) => x.toFixed(3), p1 = (x: number) => `${(100 * x).toFixed(1)}%`;

    const md = `# Coverage report (scoring v2, Quality-first)

Generated by \`tests/coverage.test.ts\` on the live database (\`public/quiz_data.json\`): all ${quizzes.toLocaleString("en-IN")} answer combinations with one seeded roll each, plus ${MULTI_PROFILES} sampled profiles x ${MULTI_ROLLS} rolls for the "ever appears" numbers. ${msPer.toFixed(2)} ms per quiz.

| Measure | v1 (2026-10-06) | v2 now | Target |
|---|---|---|---|
| Cafes that can ever appear (of ${eligibleCafes.size} with an eligible coffee) | 128 of 227 (56.4%) | ${cafesSeen.size} (${p1(cafesSeen.size / eligibleCafes.size)}) | at least 90% |
| Coffees that can ever appear (of ${eligibleCoffees} eligible) | 574 of 3,286 (17.5%) | ${coffees.size} (${p1(coffees.size / eligibleCoffees)}) | at least 45% |
| Most common cafe, share of all quizzes | BANOFFEE 31.8% | ${topName} ${p1(topShare)} | at most 18% to 20% |
| Top-10 cafes' share of all picks | 55.5% | ${p1(top10)} | at most 35% |
| Best match quality, mean / 1st percentile / minimum | 1.00 | ${f(mean[0])} / ${f(pct(slotHist[0], 0.01))} / ${f(slotMin[0])} | mean at least 0.97 |
| Close match quality | 0.97 | ${f(mean[1])} / ${f(pct(slotHist[1], 0.01))} / ${f(slotMin[1])} | mean at least 0.92 |
| Wildcard quality | 0.95 | ${f(mean[2])} / ${f(pct(slotHist[2], 0.01))} / ${f(slotMin[2])} | mean at least 0.85 |
| Results with a zero score | 0 | ${zeroScore} | 0 |

## Eligible cafes that never appear (${neverCafes.length})
${neverCafes.map((c) => `- ${c} (${data.coffees.filter((x) => x.cafe === c).length} coffees)`).join("\n") || "none"}

## Tag values in the data that no quiz answer asks for (${notAsked.length})
${notAsked.map((k) => `- ${k} (${vocab.get(k)} rows)`).join("\n") || "none"}

## Most often recommended cafes
${[...cafeQuizzes.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10).map(([c, n]) => `- ${c}: ${p1(n / quizzes)} of quizzes`).join("\n")}
`;
    mkdirSync(new URL("../test-results/", import.meta.url), { recursive: true });
    writeFileSync(new URL("../test-results/coverage.md", import.meta.url), md);
    console.log(md.split("\n").slice(0, 16).join("\n"));

    // agreed targets (REQUIREMENTS section 10)
    expect(cafesSeen.size / eligibleCafes.size).toBeGreaterThanOrEqual(0.9);
    expect(coffees.size / eligibleCoffees).toBeGreaterThanOrEqual(0.45);
    expect(topShare).toBeLessThanOrEqual(0.2);
    expect(top10).toBeLessThanOrEqual(0.35);
    expect(mean[0]).toBeGreaterThanOrEqual(0.97);
    expect(mean[1]).toBeGreaterThanOrEqual(0.92);
    expect(mean[2]).toBeGreaterThanOrEqual(0.85);
    expect(zeroScore).toBe(0);
  });
});
